"use client";

import { useMemo, useState } from "react";
import { Activity, Bot, CheckCircle2, Database, Download, Eye, FileText, HeartPulse, RefreshCw, Search, Server, ShieldCheck, Trash2, TriangleAlert } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Progress } from "@/components/ui/progress";
import { Switch } from "@/components/ui/switch";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from "@/components/ui/alert-dialog";
import { SectionCard } from "../SectionCard";
import { activities } from "../mockData";

const startingPortfolios = [
  { id: 1, name: "Tech Portfolio", owner: "Yan Lin Oo", assets: 6, risk: 72 },
  { id: 2, name: "Balanced Portfolio", owner: "Alex Morgan", assets: 8, risk: 48 },
  { id: 3, name: "Retirement Fund", owner: "Sarah Lee", assets: 12, risk: 32 },
  { id: 4, name: "Long Term Growth", owner: "John Smith", assets: 7, risk: 68 },
];
const reports = [
  { id: "RPT-1203", portfolio: "Tech Portfolio", owner: "Yan Lin Oo", score: 72, date: "Sep 2, 2026" },
  { id: "RPT-1202", portfolio: "Balanced Portfolio", owner: "Alex Morgan", score: 48, date: "Sep 2, 2026" },
  { id: "RPT-1201", portfolio: "Retirement Fund", owner: "Sarah Lee", score: 32, date: "Sep 1, 2026" },
];

export function PortfoliosPage() {
  const [items, setItems] = useState(startingPortfolios); const [query, setQuery] = useState("");
  const shown = useMemo(()=>items.filter(p=>`${p.name} ${p.owner}`.toLowerCase().includes(query.toLowerCase())),[items,query]);
  return <div className="page-stack"><div className="page-controls"><label className="page-search"><Search/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search portfolios or owners"/></label></div><SectionCard title="Investor Portfolios" description={`${shown.length} portfolios shown`}><Table><TableHeader><TableRow><TableHead>Portfolio</TableHead><TableHead>Owner</TableHead><TableHead>Assets</TableHead><TableHead>Risk score</TableHead><TableHead className="text-right">Action</TableHead></TableRow></TableHeader><TableBody>{shown.map(p=><TableRow key={p.id}><TableCell><b>{p.name}</b></TableCell><TableCell>{p.owner}</TableCell><TableCell>{p.assets}</TableCell><TableCell><span className={`risk-score ${p.risk > 65 ? "high" : p.risk > 40 ? "medium" : "low"}`}>{p.risk}</span></TableCell><TableCell className="text-right"><AlertDialog><AlertDialogTrigger asChild><Button variant="outline" size="sm"><Trash2/>Delete</Button></AlertDialogTrigger><AlertDialogContent className="admin-dialog"><AlertDialogHeader><AlertDialogTitle>Delete {p.name}?</AlertDialogTitle><AlertDialogDescription>This removes the portfolio from the frontend prototype. A backend integration should require authorization and delete the persisted record.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction variant="destructive" onClick={()=>{setItems(v=>v.filter(x=>x.id!==p.id));toast.success("Portfolio deleted.");}}>Delete portfolio</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></TableCell></TableRow>)}</TableBody></Table></SectionCard></div>;
}

export function MarketDataPage({ records, lastUpdate, onUpdate }: { records:number; lastUpdate:string; onUpdate:()=>void }) {
  return <div className="page-stack"><div className="stat-grid four"><article className="stat-card green"><div className="stat-icon"><CheckCircle2/></div><div><span>Provider</span><strong>Connected</strong><small>Yahoo Finance</small></div></article><article className="stat-card cyan"><div className="stat-icon"><Database/></div><div><span>Total Records</span><strong>{records.toLocaleString()}</strong><small>17 symbols</small></div></article><article className="stat-card orange"><div className="stat-icon"><TriangleAlert/></div><div><span>Data Gaps</span><strong>2</strong><small>Need review</small></div></article><article className="stat-card purple"><div className="stat-icon"><RefreshCw/></div><div><span>Last Update</span><strong className="smaller">{lastUpdate}</strong><small>Daily at 02:00 UTC</small></div></article></div><div className="settings-grid"><SectionCard title="Data Quality"><div className="quality-list"><p><span>Coverage</span><b>98.7%</b><Progress value={98.7}/></p><p><span>Completeness</span><b>97.3%</b><Progress value={97.3}/></p><p><span>Freshness</span><b>92.0%</b><Progress value={92}/></p></div></SectionCard><SectionCard title="Manual Update" description="Refresh all tracked symbols using the configured provider."><div className="manual-update"><Database/><p>Updates are simulated in this frontend. Connect this action to the Aura FastAPI market-data endpoint for permanent changes.</p><Button className="gradient-button" onClick={onUpdate}><RefreshCw/>Update Market Data</Button></div></SectionCard></div><SectionCard title="Update History"><Table><TableHeader><TableRow><TableHead>Started</TableHead><TableHead>Symbols</TableHead><TableHead>Records</TableHead><TableHead>Status</TableHead></TableRow></TableHeader><TableBody>{[[lastUpdate,"17",records.toLocaleString(),"Success"],["Sep 1, 2026 02:00","17","69,221","Success"],["Aug 31, 2026 02:00","16/17","65,889","Partial"]].map((r,i)=><TableRow key={i}>{r.map((x,j)=><TableCell key={j}>{j===3?<span className={`status-pill ${x.toLowerCase()}`}>{x}</span>:x}</TableCell>)}</TableRow>)}</TableBody></Table></SectionCard></div>;
}

export function ReportsPage() {
  const [selected, setSelected] = useState<typeof reports[number] | null>(null);
  function download(report: typeof reports[number]) { const blob = new Blob([JSON.stringify(report,null,2)],{type:"application/json"}); const url=URL.createObjectURL(blob); const a=document.createElement("a"); a.href=url;a.download=`${report.id}.json`;a.click();URL.revokeObjectURL(url);toast.success("Report downloaded."); }
  return <div className="page-stack"><SectionCard title="Analysis Reports" description="Review generated investor risk reports."><Table><TableHeader><TableRow><TableHead>Report</TableHead><TableHead>Portfolio</TableHead><TableHead>Owner</TableHead><TableHead>Risk</TableHead><TableHead>Date</TableHead><TableHead className="text-right">Actions</TableHead></TableRow></TableHeader><TableBody>{reports.map(r=><TableRow key={r.id}><TableCell><b>{r.id}</b></TableCell><TableCell>{r.portfolio}</TableCell><TableCell>{r.owner}</TableCell><TableCell><span className={`risk-score ${r.score>65?"high":r.score>40?"medium":"low"}`}>{r.score}</span></TableCell><TableCell>{r.date}</TableCell><TableCell className="text-right"><div className="inline-actions"><Button variant="outline" size="icon-sm" onClick={()=>setSelected(r)} aria-label={`View ${r.id}`}><Eye/></Button><Button variant="outline" size="icon-sm" onClick={()=>download(r)} aria-label={`Download ${r.id}`}><Download/></Button></div></TableCell></TableRow>)}</TableBody></Table></SectionCard><Dialog open={!!selected} onOpenChange={v=>!v&&setSelected(null)}><DialogContent className="admin-dialog"><DialogHeader><DialogTitle>{selected?.id}</DialogTitle><DialogDescription>Immutable analysis report summary.</DialogDescription></DialogHeader>{selected&&<div className="report-detail"><FileText/><p><span>Portfolio</span><b>{selected.portfolio}</b></p><p><span>Owner</span><b>{selected.owner}</b></p><p><span>Risk score</span><b>{selected.score}/100</b></p><p><span>Generated</span><b>{selected.date}</b></p></div>}<DialogFooter><Button onClick={()=>selected&&download(selected)}>Download JSON</Button></DialogFooter></DialogContent></Dialog></div>;
}

export function HealthPage() { const services=[["API Server","Healthy",Server,18],["PostgreSQL","Connected",Database,23],["Market Data Provider","Available",RefreshCw,31],["Analytics Engine","Available",Activity,16],["Authentication","Healthy",ShieldCheck,14]] as const; return <div className="page-stack"><SectionCard className="health-hero"><div className="health-orb"><HeartPulse/></div><h2>All Systems Operational</h2><p>Aura services are responding normally.</p></SectionCard><div className="health-grid">{services.map(([name,status,Icon,response])=><SectionCard key={name}><div className="service-card"><Icon/><div><b>{name}</b><p>Response time {response} ms</p></div><span>{status}</span></div></SectionCard>)}</div></div>; }

export function AiOversightPage() { const [logging,setLogging]=useState(true); const [adviceGuard,setAdviceGuard]=useState(true); return <div className="page-stack"><SectionCard className="coming-soon"><Bot/><span>PLANNED</span><h2>AI Oversight</h2><p>This control center will monitor grounded answers, refusals, limitations and source use after the Aura AI provider is configured.</p></SectionCard><div className="settings-grid"><SectionCard title="Future Guardrails"><div className="setting-row"><div><b>Audit AI interactions</b><p>Retain structured metadata for administrator review.</p></div><Switch checked={logging} onCheckedChange={setLogging}/></div><div className="setting-row"><div><b>Investment-advice refusal</b><p>Keep deterministic refusal rules enabled.</p></div><Switch checked={adviceGuard} onCheckedChange={setAdviceGuard}/></div></SectionCard><SectionCard title="Current Status"><div className="status-explainer"><ShieldCheck/><p><b>Backend route prepared</b><span>The feature remains unavailable until a provider is configured and React integration is completed.</span></p></div></SectionCard></div></div>; }

export function ActivityPage() { const [query,setQuery]=useState(""); const filtered=activities.filter(x=>x.join(" ").toLowerCase().includes(query.toLowerCase())); return <div className="page-stack"><div className="page-controls"><label className="page-search"><Search/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search activity logs"/></label></div><SectionCard title="Administrator Activity" description="Local prototype audit events"><div className="full-activity">{filtered.map(([title,detail,time])=><article key={title+time}><span><Activity/></span><div><b>{title}</b><p>{detail}</p></div><time>{time}</time></article>)}</div></SectionCard></div>; }
