"use client";
import { useCallback, useState, type ReactNode } from "react";
import { Activity, Bot, Database, HeartPulse } from "lucide-react";
import { adminApi } from "@/lib/adminApi";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { SectionCard } from "../SectionCard";
import { ApiState, Filter, Pagination, humanize, utc } from "../ApiState";
import { useAdminQuery } from "../useAdminQuery";

function RecordsTable({ headings, rows }: { headings: string[]; rows: { id: string; cells: ReactNode[] }[] }) {
  return <Table><TableHeader><TableRow>{headings.map(heading => <TableHead key={heading}>{heading}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map(row => <TableRow key={row.id}>{row.cells.map((cell, index) => <TableCell key={index}>{cell}</TableCell>)}</TableRow>)}</TableBody></Table>;
}
function Status({ value }: { value: string }) { return <span className={`status-pill api-status-${value.toLowerCase()}`}>{humanize(value)}</span>; }
function Dates({ from, to, change }: { from: string; to: string; change: (key: "from" | "to", value: string) => void }) {
  return <><label className="api-filter">From (UTC)<Input aria-label="From date UTC" type="date" value={from} onChange={event => change("from", event.target.value)}/></label><label className="api-filter">To (UTC)<Input aria-label="To date UTC" type="date" value={to} onChange={event => change("to", event.target.value)}/></label></>;
}
function timeRange(from: string, to: string) { return { created_from: from ? `${from}T00:00:00Z` : undefined, created_to: to ? `${to}T23:59:59.999999Z` : undefined }; }

export function PortfoliosPage() {
  const query = useAdminQuery(adminApi.dashboard);
  return <div className="page-stack"><SectionCard title="Investor Portfolios" description="Aggregate retained counts from the admin dashboard."><ApiState {...query}/>{query.data && <div className="data-pairs"><p><span>Total</span><b>{query.data.portfolios.total}</b></p><p><span>Current</span><b>{query.data.portfolios.current}</b></p><p><span>Planned</span><b>{query.data.portfolios.planned}</b></p><p><span>Legacy</span><b>{query.data.portfolios.legacy}</b></p></div>}<p className="api-message">The backend does not yet provide a global admin portfolio directory or deletion API. Individual portfolios cannot be browsed or deleted here.</p></SectionCard></div>;
}
export function ReportsPage() {
  const query = useAdminQuery(adminApi.dashboard);
  return <div className="page-stack"><SectionCard title="Analysis Reports" description="Counts of retained saved records, not analysis executions."><ApiState {...query}/>{query.data && <RecordsTable headings={["Saved record", "Total", "Today (UTC)", "Yesterday (UTC)", "Last 7 days"]} rows={[["Reports", query.data.saved_reports], ["Simulations", query.data.saved_simulations]].map(([label, counts]) => { const value = counts as typeof query.data.saved_reports; return { id: String(label), cells: [String(label), value.total, value.today, value.yesterday, value.last_7_days] }; })}/>}<p className="api-message">Global admin report browsing and downloading are not supported yet.</p></SectionCard></div>;
}

export function MarketDataPage() {
  const inventory = useAdminQuery(adminApi.inventory);
  const status = useAdminQuery(adminApi.marketStatus);
  const [filters, setFilters] = useState({ symbol: "", from: "", to: "", offset: 0 });
  const load = useCallback((signal: AbortSignal) => adminApi.observations({ symbol: filters.symbol, date_from: filters.from, date_to: filters.to, offset: filters.offset, limit: 25 }, signal), [filters]);
  const observations = useAdminQuery(load);
  return <div className="page-stack"><div className="settings-grid"><SectionCard title="Stored Market Data" description="Asset and FX observations; no live provider probe."><ApiState {...inventory}/>{inventory.data && <div className="data-pairs"><p><span>Total records</span><b>{inventory.data.total_records.toLocaleString()}</b></p><p><span>Stored / required instruments</span><b>{inventory.data.stored_symbols} / {inventory.data.required_symbols}</b></p><p><span>Current required</span><b>{inventory.data.current_required_symbols}</b></p><p><span>Stale / missing required</span><b>{inventory.data.stale_required_symbols} / {inventory.data.missing_required_symbols}</b></p><p><span>Unexpected symbols</span><b>{inventory.data.unexpected_symbols}</b></p></div>}</SectionCard><SectionCard title="Daily Refresh Status" description="Latest recorded attempt; a complete update history is not available."><ApiState {...status}/>{status.data && <div className="data-pairs"><p><span>Worker</span><b><Status value={status.data.worker_status}/></b></p><p><span>Heartbeat</span><b>{utc(status.data.worker_last_seen_at)}</b></p><p><span>Last run</span><b><Status value={status.data.last_run_status}/></b></p><p><span>Last attempt / complete</span><b>{utc(status.data.last_attempt_at)} / {utc(status.data.last_complete_at)}</b></p><p><span>Next scheduled</span><b>{utc(status.data.next_scheduled_at)}</b></p><p><span>Rows stored in last attempt</span><b>{status.data.stored_count}</b></p><p><span>Updated symbols</span><b>{status.data.updated_symbols.join(", ") || "None"}</b></p><p><span>Failed symbols</span><b>{status.data.failed_symbols.join(", ") || "None"}</b></p><p><span>Error</span><b>{status.data.error_code ? humanize(status.data.error_code) : "None recorded"}</b></p></div>}<Button className="gradient-button" disabled><Database/>Update Market Data</Button><p className="api-caption">Manual refresh is not supported by the admin API.</p></SectionCard></div>
    <SectionCard title="Instrument Inventory" description="Select an instrument to browse its stored observations. Freshness does not prove historical completeness."><ApiState {...inventory}/>{inventory.data && <RecordsTable headings={["Symbol", "Kind", "Required", "Records", "First date", "Latest date", "Latest adjusted close", "Quote currency", "Freshness"]} rows={inventory.data.instruments.map(item => ({ id: item.symbol, cells: [<Button key="symbol" variant="ghost" size="sm" onClick={() => setFilters(value => ({ ...value, symbol: item.symbol, offset: 0 }))}>{item.symbol}</Button>, humanize(item.kind), item.required_for_refresh ? "Yes" : "No", item.total_records, item.first_price_date ?? "—", item.latest_price_date ?? "—", item.latest_adjusted_close ?? "—", item.quote_currency ?? "—", <Status key="status" value={item.freshness}/>] }))}/>}</SectionCard>
    <SectionCard title="Stored Observations" description="Exact stored decimal prices; asset and FX units follow the inventory."><div className="page-controls api-controls"><label className="api-filter">Symbol<Input aria-label="Observation symbol" maxLength={64} value={filters.symbol} onChange={event => setFilters(value => ({ ...value, symbol: event.target.value.toUpperCase(), offset: 0 }))}/></label><Dates from={filters.from} to={filters.to} change={(key, value) => setFilters(current => ({ ...current, [key]: value, offset: 0 }))}/></div><ApiState {...observations}/>{observations.data && <><RecordsTable headings={["Symbol", "Date", "Adjusted close", "Volume", "Source"]} rows={observations.data.items.map(item => ({ id: `${item.symbol}-${item.date}`, cells: [item.symbol, item.date, item.adjusted_close, item.volume ?? "—", item.source] }))}/>{observations.data.items.length === 0 && <p className="api-message">No stored observations match these filters.</p>}<Pagination {...observations.data} onChange={offset => setFilters(value => ({ ...value, offset }))}/></>}</SectionCard>
  </div>;
}
export function HealthPage() {
  const query = useAdminQuery(adminApi.health);
  return <div className="page-stack"><SectionCard className="health-hero"><div className="health-orb"><HeartPulse/></div><ApiState {...query}/>{query.data && <><h2>{humanize(query.data.status)}</h2><p>Checked {utc(query.data.checked_at)} · Partial coverage. Unknown and unchecked services have no verified health result.</p></>}</SectionCard>{query.data && <div className="health-grid">{query.data.checks.map(check => <SectionCard key={check.component}><div className="service-card"><Activity/><div><b>{humanize(check.component)}</b><p>{humanize(check.reason)}</p><p>{check.latency_ms === null ? "Latency not measured" : `Measured latency: ${check.latency_ms} ms`}</p></div><Status value={check.status}/></div></SectionCard>)}</div>}</div>;
}
export function AiOversightPage() {
  const summary = useAdminQuery(adminApi.aiSummary);
  const [filters, setFilters] = useState({ outcome: "", provider_kind: "", refusal_stage: "", error_code: "", from: "", to: "", offset: 0 });
  const load = useCallback((signal: AbortSignal) => { const { from, to, ...query } = filters; return adminApi.aiRequests({ ...query, ...timeRange(from, to), limit: 25 }, signal); }, [filters]);
  const requests = useAdminQuery(load);
  const change = (key: keyof typeof filters, value: string) => setFilters(current => ({ ...current, [key]: value, offset: 0 }));
  return <div className="page-stack"><div className="settings-grid"><SectionCard title="AI Monitoring" description="Retained operational metadata. Telemetry writes are best effort."><ApiState {...summary}/>{summary.data && <div className="data-pairs"><p><span>Total / completed / refused / errors</span><b>{summary.data.total} / {summary.data.completed} / {summary.data.refused} / {summary.data.errors}</b></p><p><span>Provider calls</span><b>{summary.data.provider_calls}</b></p><p><span>Input / output refusals</span><b>{summary.data.input_refusals} / {summary.data.output_refusals}</b></p><p><span>Average duration</span><b>{summary.data.average_duration_ms === null ? "Not recorded" : `${summary.data.average_duration_ms} ms`}</b></p><p><span>Last recorded</span><b>{utc(summary.data.last_recorded_at)}</b></p></div>}</SectionCard><SectionCard title="Provider Configuration"><Bot/><ApiState {...summary}/>{summary.data && <div className="data-pairs"><p><span>Configured provider</span><b>{summary.data.configuration.configured_provider ?? "None"}</b></p><p><span>Model / credential configured</span><b>{summary.data.configuration.model_configured ? "Yes" : "No"} / {summary.data.configuration.credential_configured ? "Yes" : "No"}</b></p><p><span>Configuration ready</span><b>{summary.data.configuration.ready ? "Yes" : "No"}</b></p><p><span>Connectivity</span><b>Not checked</b></p><p><span>Investment-advice guard</span><b>Enabled</b></p></div>}<p className="api-caption">Monitoring makes no provider calls and does not expose prompts, answers, credentials, or user identities.</p></SectionCard></div>
    <SectionCard title="AI Request Metadata"><div className="page-controls api-controls"><Filter label="Outcome" value={filters.outcome} options={["COMPLETED", "REFUSED", "ERROR"]} onChange={value => change("outcome", value)}/><Filter label="Provider" value={filters.provider_kind} options={["openai", "groq", "custom"]} onChange={value => change("provider_kind", value)}/><Filter label="Refusal stage" value={filters.refusal_stage} options={["INPUT", "OUTPUT"]} onChange={value => change("refusal_stage", value)}/><Filter label="Error" value={filters.error_code} options={["CONTEXT_UNAVAILABLE", "REPORT_UNAVAILABLE", "SIMULATION_UNAVAILABLE", "MARKET_DATA_UNAVAILABLE", "HOLDING_STATE_INVALID", "PROVIDER_UNAVAILABLE", "PROVIDER_TIMEOUT", "INVALID_PROVIDER_RESPONSE", "UNSAFE_PROVIDER_OUTPUT", "INTERNAL_ERROR"]} onChange={value => change("error_code", value)}/><Dates from={filters.from} to={filters.to} change={change}/></div><ApiState {...requests}/>{requests.data && <><RecordsTable headings={["Started (UTC)", "Outcome / HTTP", "Provider / called", "Duration", "Refusal / reason", "Error", "Sources", "Limitations"]} rows={requests.data.items.map(item => ({ id: item.id, cells: [utc(item.started_at), `${humanize(item.outcome)} / ${item.http_status}`, `${item.provider_kind ?? "None"} / ${item.provider_called ? "Yes" : "No"}`, `${item.duration_ms} ms`, `${item.refusal_stage ?? "—"} / ${item.guardrail_reason ? humanize(item.guardrail_reason) : "—"}`, item.error_code ? humanize(item.error_code) : "—", [item.has_portfolio_source && "Portfolio", item.has_report_source && "Report", item.has_simulation_source && "Simulation"].filter(Boolean).join(", ") || "None", item.limitation_count] }))}/>{requests.data.items.length === 0 && <p className="api-message">No retained AI requests match these filters.</p>}<Pagination {...requests.data} onChange={offset => setFilters(value => ({ ...value, offset }))}/></>}</SectionCard>
  </div>;
}
export function ActivityPage() {
  const [filters, setFilters] = useState({ action: "", actor_kind: "", from: "", to: "", offset: 0 });
  const load = useCallback((signal: AbortSignal) => { const { from, to, ...query } = filters; return adminApi.audit({ ...query, ...timeRange(from, to), limit: 25 }, signal); }, [filters]);
  const query = useAdminQuery(load);
  const change = (key: keyof typeof filters, value: string) => setFilters(current => ({ ...current, [key]: value, offset: 0 }));
  return <div className="page-stack"><SectionCard title="Administrator Activity" description="Persisted audit history. Currently records administrator bootstrap events."><div className="page-controls api-controls"><Filter label="Action" value={filters.action} options={["ADMIN_BOOTSTRAPPED"]} onChange={value => change("action", value)}/><Filter label="Actor" value={filters.actor_kind} options={["OPERATOR", "ADMIN"]} onChange={value => change("actor_kind", value)}/><Dates from={filters.from} to={filters.to} change={change}/></div><ApiState {...query}/>{query.data && <><RecordsTable headings={["Time (UTC)", "Action", "Actor", "Target user ID", "Role change"]} rows={query.data.items.map(event => ({ id: event.id, cells: [utc(event.created_at), humanize(event.action), `${humanize(event.actor_kind)}${event.actor_user_id ? ` · ${event.actor_user_id}` : ""}`, event.target_id, `${humanize(event.details.previous_role)} → ${humanize(event.details.new_role)}`] }))}/>{query.data.items.length === 0 && <p className="api-message">No retained audit events match these filters.</p>}<Pagination {...query.data} onChange={offset => setFilters(value => ({ ...value, offset }))}/></>}</SectionCard></div>;
}
