import { StyleSheet } from 'react-native';
import { colors, spacing } from '../theme/theme';

export const forecastingStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.background },
  content: { padding: spacing.lg, paddingBottom: 110, gap: spacing.md },
  card: { gap: spacing.md },
  row: { flexDirection: 'row', gap: spacing.sm, flexWrap: 'wrap' },
  option: { minHeight: 44, paddingHorizontal: 12, paddingVertical: 9, borderRadius: 12, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surfaceAlt, justifyContent: 'center' },
  active: { borderColor: colors.primary, backgroundColor: colors.selectedBackground },
  optionText: { color: colors.textSecondary, fontSize: 11, fontWeight: '800' },
  activeText: { color: colors.primary },
  disabled: { opacity: 0.45 },
  tiny: { color: colors.muted, fontSize: 9, marginTop: 3 },
  heading: { color: colors.text, fontSize: 17, fontWeight: '900' },
  title: { color: colors.text, fontSize: 22, fontWeight: '900' },
  label: { color: colors.textSecondary, fontSize: 12, fontWeight: '700' },
  body: { color: colors.textSecondary, fontSize: 11, lineHeight: 17 },
  note: { color: colors.muted, fontSize: 10, lineHeight: 16 },
  badge: { alignSelf: 'flex-start', paddingHorizontal: 9, paddingVertical: 6, borderRadius: 9, backgroundColor: colors.warningBackground, color: colors.warning, fontSize: 10, fontWeight: '800' },
  education: { borderRadius: 12, borderWidth: 1, borderColor: colors.border, padding: 12, backgroundColor: colors.cyanBackground, color: colors.textSecondary, fontSize: 10, lineHeight: 17 },
  search: { minHeight: 44, borderRadius: 12, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surfaceAlt, paddingHorizontal: 12, color: colors.text, fontSize: 12 },
  assetPicker: { maxHeight: 180 },
  assetOption: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: spacing.sm, minHeight: 48, padding: 10, borderRadius: 11, borderWidth: 1, borderColor: colors.border, marginBottom: 6 },
  assetName: { flex: 1, color: colors.textSecondary, fontSize: 11 },
  metric: { gap: spacing.sm },
  number: { color: colors.primary, fontSize: 30, fontWeight: '900' },
  negative: { color: colors.danger },
  dataRow: { flexDirection: 'row', alignItems: 'flex-start', gap: spacing.sm, paddingVertical: 8, borderBottomWidth: 1, borderBottomColor: colors.borderSoft },
  dataLabel: { flex: 1, color: colors.muted, fontSize: 10, lineHeight: 16 },
  dataValue: { flex: 1, color: colors.textSecondary, fontSize: 11, lineHeight: 16, fontWeight: '700', textAlign: 'right' },
  driver: { gap: 7 },
  driverTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', minHeight: 44 },
  link: { color: colors.primary, fontSize: 12, fontWeight: '800' },
  track: { position: 'relative', height: 14, borderRadius: 4, backgroundColor: colors.surfaceAlt },
  origin: { position: 'absolute', top: -3, bottom: -3, width: 1, backgroundColor: colors.muted, zIndex: 1 },
  bar: { position: 'absolute', height: '100%', borderRadius: 3, backgroundColor: colors.primary },
  negativeBar: { backgroundColor: colors.blue },
  detailsButton: { minHeight: 44, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  refresh: { minHeight: 44, borderRadius: 10, paddingHorizontal: 10, justifyContent: 'center', alignItems: 'center', borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surfaceAlt },
});
